### ISSUE TITLE
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

### ISSUE THREAD

**Issue by takeyamayuki** [Vegetebird/StridedTransformer-Pose3D#12]
After training the model according to README, I typed `python demo/vis.py --video back.webm` and got the following error.

```bash
(venv) yuki@take-ubuntu2:~/workspace/StridedTransformer-Pose3D$ python demo/vis.py --video back.webm

Generating 2D pose...
100%|███████████████████████████████████████████████████████████████████████████| 499/499 [00:44<00:00, 11.21it/s]
Generating 2D pose successful!

Generating 3D pose...
  0%|                                                                                     | 0/499 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo/vis.py", line 276, in <module>
    get_pose3D(video_path, output_dir)
  File "demo/vis.py", line 222, in get_pose3D
    show3Dpose( post_out, ax)
  File "demo/vis.py", line 68, in show3Dpose
    ax.set_aspect('equal')
  File "/home/yuki/workspace/StridedTransformer-Pose3D/venv/lib/python3.6/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 324, in set_aspect
    "Axes3D currently only supports the aspect argument "
NotImplementedError: Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.
```
I looked into this error and found that the following line seems to be the cause.

https://github.com/Vegetebird/StridedTransformer-Pose3D/blob/5fbb0248ce6dd7db51f669422ed2dc86556e3f7a/demo/vis.py#L68

I replaced this line with `ax.set_aspect('auto')` or `ax.set_box_aspect([1,1,1])` according to https://github.com/fabro66/GAST-Net-3DPoseEstimation/issues/51 and it works fine.

Why do you write `ax.set_aspect('equal')`?

If there is no particular reason then it needs to be fixed.

**Comment by Vegetebird** [comment]
It works fine in matplotlib==2.2.2, may be you could try it.

**Comment by takeyamayuki** [comment]
ok. thanks!
